// LocalizedSymbolNames.swift
// GENERATED — do not edit by hand.
// Run ios/Scripts/generate-ipa-mapping.sh to regenerate.
//
// Source SHA256: 646b5164ab2fd9fc635471d582dbc3987dc533d53d36441f469394a8ba0b4db8

// swiftlint:disable all

import Foundation

public enum LocalizedSymbolNames {

    /// SHA256 of companion-app/src/data/ipa-names.ts at codegen time.
    public static let sourceHash: String = "646b5164ab2fd9fc635471d582dbc3987dc533d53d36441f469394a8ba0b4db8"

    /// Maps IPA symbol string → English name. Includes the full library, not just mapped variants.
    public static let english: [String: String] = [
        "i": "close front unrounded vowel",
        "iː": "long close front unrounded vowel",
        "ɪ": "near-close near-front unrounded vowel",
        "e": "close-mid front unrounded vowel",
        "ɛ": "open-mid front unrounded vowel",
        "æ": "near-open front unrounded vowel",
        "a": "open front unrounded vowel",
        "ɑ": "open back unrounded vowel",
        "ɑː": "long open back unrounded vowel",
        "ɒ": "open back rounded vowel",
        "ɔ": "open-mid back rounded vowel",
        "ɔː": "long open-mid back rounded vowel",
        "o": "close-mid back rounded vowel",
        "ʊ": "near-close near-back rounded vowel",
        "u": "close back rounded vowel",
        "uː": "long close back rounded vowel",
        "ʌ": "open-mid back unrounded vowel",
        "ə": "schwa",
        "ɚ": "r-coloured schwa",
        "ɜ": "open-mid central unrounded vowel",
        "ɜː": "long open-mid central unrounded vowel",
        "ɝ": "r-coloured open-mid central vowel",
        "ɨ": "close central unrounded vowel",
        "ʉ": "close central rounded vowel",
        "ɵ": "close-mid central rounded vowel",
        "ɐ": "near-open central vowel",
        "ɯ": "close back unrounded vowel",
        "ɤ": "close-mid back unrounded vowel",
        "ʏ": "near-close near-front rounded vowel",
        "œ": "open-mid front rounded vowel",
        "eɪ": "diphthong",
        "aɪ": "diphthong",
        "ɔɪ": "diphthong",
        "aʊ": "diphthong",
        "əʊ": "diphthong",
        "ɪə": "diphthong",
        "eə": "diphthong",
        "ʊə": "diphthong",
        "p": "voiceless bilabial plosive",
        "b": "voiced bilabial plosive",
        "t": "voiceless alveolar plosive",
        "d": "voiced alveolar plosive",
        "k": "voiceless velar plosive",
        "g": "voiced velar plosive",
        "ʈ": "voiceless retroflex plosive",
        "ɖ": "voiced retroflex plosive",
        "c": "voiceless palatal plosive",
        "ɟ": "voiced palatal plosive",
        "q": "voiceless uvular plosive",
        "ɢ": "voiced uvular plosive",
        "ʔ": "glottal stop",
        "f": "voiceless labiodental fricative",
        "v": "voiced labiodental fricative",
        "θ": "voiceless dental fricative",
        "ð": "voiced dental fricative",
        "s": "voiceless alveolar fricative",
        "z": "voiced alveolar fricative",
        "ʃ": "voiceless postalveolar fricative",
        "ʒ": "voiced postalveolar fricative",
        "ʂ": "voiceless retroflex fricative",
        "ʐ": "voiced retroflex fricative",
        "ç": "voiceless palatal fricative",
        "ʝ": "voiced palatal fricative",
        "x": "voiceless velar fricative",
        "ɣ": "voiced velar fricative",
        "χ": "voiceless uvular fricative",
        "ʁ": "voiced uvular fricative",
        "ħ": "voiceless pharyngeal fricative",
        "ʕ": "voiced pharyngeal fricative",
        "h": "voiceless glottal fricative",
        "ɦ": "voiced glottal fricative",
        "ɕ": "voiceless alveolopalatal fricative",
        "ʑ": "voiced alveolopalatal fricative",
        "ɸ": "voiceless bilabial fricative",
        "β": "voiced bilabial fricative",
        "ɧ": "voiceless palatal-velar fricative",
        "m": "voiced bilabial nasal",
        "ɱ": "voiced labiodental nasal",
        "n": "voiced alveolar nasal",
        "ɳ": "voiced retroflex nasal",
        "ɲ": "voiced palatal nasal",
        "ŋ": "voiced velar nasal",
        "ɴ": "voiced uvular nasal",
        "ɹ": "voiced alveolar approximant",
        "ɻ": "voiced retroflex approximant",
        "j": "voiced palatal approximant",
        "ɰ": "voiced velar approximant",
        "w": "voiced labial-velar approximant",
        "ʍ": "voiceless labial-velar fricative",
        "ɥ": "voiced labial-palatal approximant",
        "l": "voiced alveolar lateral approximant",
        "ɫ": "velarized alveolar lateral",
        "ɭ": "voiced retroflex lateral",
        "ʎ": "voiced palatal lateral",
        "ʋ": "voiced labiodental approximant",
        "r": "voiced alveolar trill",
        "ʀ": "voiced uvular trill",
        "ʙ": "voiced bilabial trill",
        "ɾ": "voiced alveolar tap",
        "ɽ": "voiced retroflex flap",
        "ɺ": "voiced alveolar lateral flap",
        "ɬ": "voiceless alveolar lateral fricative",
        "ɮ": "voiced alveolar lateral fricative",
        "t͡ʃ": "voiceless postalveolar affricate",
        "d͡ʒ": "voiced postalveolar affricate",
        "t͡s": "voiceless alveolar affricate",
        "tʃ": "voiceless postalveolar affricate (no tie)",
        "dʒ": "voiced postalveolar affricate (no tie)",
        "ɓ": "voiced bilabial implosive",
        "ɗ": "voiced alveolar implosive",
        "ʄ": "voiced palatal implosive",
        "ɠ": "voiced velar implosive",
        "ʛ": "voiced uvular implosive",
        "ʘ": "bilabial click",
        "ǀ": "dental click",
        "ǃ": "alveolar click",
        "ǂ": "palatal click",
        "ǁ": "lateral click",
        "ˈ": "primary stress",
        "ˌ": "secondary stress",
        "ː": "long",
        "ˑ": "half-long",
        "˥": "extra-high tone",
        "˦": "high tone",
        "˧": "mid tone",
        "˨": "low tone",
        "˩": "extra-low tone",
        "ʰ": "aspirated",
        "ʷ": "labialized",
        "ʲ": "palatalized",
        "ˠ": "velarized",
        "ˤ": "pharyngealized",
        "ⁿ": "nasal release",
        "ˡ": "lateral release",
        "ã": "nasalized open front vowel",
        "ẽ": "nasalized close-mid front vowel",
        "õ": "nasalized close-mid back rounded vowel",
    ]
}
